Update project URL for Czech Technical University (#6485) (#6487)
I think this should fix this error:

```
  File "/home/runner/work/ros2_documentation/ros2_documentation/plugins/sphinx_adopters.py", line 79, in run
    raise ExtensionError(
sphinx.errors.ExtensionError: Adopters YAML validation failed:
  - Entry 8 (Czech Technical University in Prague/Vision for Robotics and Autonomous Systems): "project_url" URL is not reachable: https://cyber.felk.cvut.cz/vras/ (The read operation timed out)
multiprocessing.pool.RemoteTraceback:
"""
```

https://github.com/ros2/ros2_documentation/actions/runs/25147132841/job/73709342605?pr=6484


(cherry picked from commit 129cc526b03b439b2f69178e8d984747dd697706)

Signed-off-by: Shane Loretz <shane.loretz@gmail.com>
Co-authored-by: Shane Loretz <shane.loretz@gmail.com>